project_id = "nodhzumnsioftsftsbsn"

[functions.chat-with-ai]
verify_jwt = false

[functions.check-sla]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = true

[functions.generate-insights]
verify_jwt = true

[functions.generate-manual-insights]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.send-insights-email]
verify_jwt = false

[functions.simulate-financing]
verify_jwt = false

[functions.generate-faq-from-knowledge]
verify_jwt = false

[functions.update-bank-rates]
verify_jwt = false
